services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tender_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/tender_db?sslmode=disable
    command: ["sh", "-c", "goose -dir /app/migrations postgres 'user=postgres password=postgres dbname=tender_db host=db port=5432 sslmode=disable' up && ./app"]

volumes:
  pgdata: